const assert = require('node:assert/strict');
const { existsSync, readFileSync, readdirSync } = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const test = require('node:test');

const root = path.resolve(__dirname, '..', '..');
const pythonProject = path.join(root, 'proto', 'python');
const pythonRoot = path.join(pythonProject, 'src', 'aiflow', 'v1');
const protos = ['common', 'sandbox'];

test('contains the generated Python protobuf surface for the sandbox', () => {
  const projectPath = path.join(pythonProject, 'pyproject.toml');
  assert.ok(existsSync(projectPath), 'proto/python/pyproject.toml must exist');
  assert.ok(existsSync(path.join(pythonRoot, '__init__.py')));

  for (const name of protos) {
    const pyFile = path.join(pythonRoot, `${name}_pb2.py`);
    const pyiFile = path.join(pythonRoot, `${name}_pb2.pyi`);
    assert.ok(existsSync(pyFile), `${name}_pb2.py must exist`);
    assert.ok(existsSync(pyiFile), `${name}_pb2.pyi must exist`);
    assert.match(readFileSync(pyFile, 'utf8'), /Generated by .*DO NOT EDIT!/i);
  }
  assert.ok(existsSync(path.join(pythonRoot, 'sandbox_pb2_grpc.py')));

  const allowed = new Set([
    '__init__.py',
    'common_pb2.py',
    'common_pb2.pyi',
    'common_pb2_grpc.py',
    'sandbox_pb2.py',
    'sandbox_pb2.pyi',
    'sandbox_pb2_grpc.py',
  ]);
  const actual = new Set(readdirSync(pythonRoot).filter((name) => name !== '__pycache__'));
  assert.deepEqual(actual, allowed);

  const project = readFileSync(projectPath, 'utf8');
  assert.match(project, /requires-python = ">=3\.13,<3\.14"/);
  assert.match(project, /"protobuf==6\.31\.1"/);
  assert.match(project, /"grpcio==1\.74\.0"/);
});

test('imports the shared Python protobuf package', () => {
  const result = spawnSync(
    'uv',
    [
      'run',
      '--offline',
      '--project',
      pythonProject,
      'python',
      '-c',
      [
        'from aiflow.v1 import common_pb2',
        'from aiflow.v1 import sandbox_pb2, sandbox_pb2_grpc',
        "print('python proto imports ok')",
      ].join('; '),
    ],
    { cwd: root, encoding: 'utf8' },
  );

  assert.equal(result.status, 0, result.stderr || result.stdout);
  assert.match(result.stdout, /python proto imports ok/);
});
