const assert = require('node:assert/strict');
const { existsSync, readFileSync, readdirSync } = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const test = require('node:test');

const root = path.resolve(__dirname, '..', '..');
const goRoot = path.join(
  root,
  'flowai-studio-control-plane',
  'internal',
  'gen',
  'aiflow',
  'v1',
);
const pythonProject = path.join(root, 'proto', 'python');
const pythonRoot = path.join(pythonProject, 'src', 'aiflow', 'v1');
const protos = ['common', 'execution', 'documents', 'retrieval', 'mcp', 'models', 'sandbox'];
const services = ['execution', 'documents', 'retrieval', 'mcp', 'models', 'sandbox'];

test('generates the complete Go and Python protobuf surface', () => {
  const projectPath = path.join(pythonProject, 'pyproject.toml');
  assert.ok(existsSync(projectPath), 'proto/python/pyproject.toml must exist');
  assert.ok(existsSync(path.join(pythonRoot, '__init__.py')), 'Python v1 package marker must exist');

  for (const name of protos) {
    const goFile = path.join(goRoot, `${name}.pb.go`);
    const pyFile = path.join(pythonRoot, `${name}_pb2.py`);
    const pyiFile = path.join(pythonRoot, `${name}_pb2.pyi`);
    assert.ok(existsSync(goFile), `${name}.pb.go must exist`);
    assert.ok(existsSync(pyFile), `${name}_pb2.py must exist`);
    assert.ok(existsSync(pyiFile), `${name}_pb2.pyi must exist`);
    assert.match(readFileSync(goFile, 'utf8'), /Code generated .* DO NOT EDIT\./);
    assert.match(readFileSync(pyFile, 'utf8'), /Generated by .*DO NOT EDIT!/i);
  }

  for (const name of services) {
    assert.ok(existsSync(path.join(goRoot, `${name}_grpc.pb.go`)), `${name}_grpc.pb.go must exist`);
    assert.ok(
      existsSync(path.join(pythonRoot, `${name}_pb2_grpc.py`)),
      `${name}_pb2_grpc.py must exist`,
    );
  }

  const allowedGo = new Set([
    ...protos.map((name) => `${name}.pb.go`),
    ...services.map((name) => `${name}_grpc.pb.go`),
  ]);
  const actualGo = new Set(readdirSync(goRoot));
  assert.deepEqual(actualGo, allowedGo);

  const project = readFileSync(projectPath, 'utf8');
  assert.match(project, /requires-python = ">=3\.13,<3\.14"/);
  assert.match(project, /"protobuf==6\.31\.1"/);
  assert.match(project, /"grpcio==1\.74\.0"/);
});

test('imports the shared Python protobuf package', () => {
  const result = spawnSync(
    'uv',
    [
      'run',
      '--project',
      pythonProject,
      'python',
      '-c',
      [
        'from aiflow.v1 import common_pb2',
        'from aiflow.v1 import execution_pb2, execution_pb2_grpc',
        'from aiflow.v1 import sandbox_pb2, sandbox_pb2_grpc',
        "print('python proto imports ok')",
      ].join('; '),
    ],
    { cwd: root, encoding: 'utf8' },
  );

  assert.equal(result.status, 0, result.stderr || result.stdout);
  assert.match(result.stdout, /python proto imports ok/);
});
