# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aiflow.v1 import documents_pb2 as aiflow_dot_v1_dot_documents__pb2


class DocumentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestDocument = channel.stream_unary(
                '/aiflow.v1.DocumentService/IngestDocument',
                request_serializer=aiflow_dot_v1_dot_documents__pb2.IngestDocumentRequest.SerializeToString,
                response_deserializer=aiflow_dot_v1_dot_documents__pb2.IngestDocumentResponse.FromString,
                _registered_method=True)


class DocumentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IngestDocument(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestDocument': grpc.stream_unary_rpc_method_handler(
                    servicer.IngestDocument,
                    request_deserializer=aiflow_dot_v1_dot_documents__pb2.IngestDocumentRequest.FromString,
                    response_serializer=aiflow_dot_v1_dot_documents__pb2.IngestDocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiflow.v1.DocumentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiflow.v1.DocumentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IngestDocument(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/aiflow.v1.DocumentService/IngestDocument',
            aiflow_dot_v1_dot_documents__pb2.IngestDocumentRequest.SerializeToString,
            aiflow_dot_v1_dot_documents__pb2.IngestDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
