# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aiflow.v1 import mcp_pb2 as aiflow_dot_v1_dot_mcp__pb2


class McpServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ManageMcp = channel.unary_unary(
                '/aiflow.v1.McpService/ManageMcp',
                request_serializer=aiflow_dot_v1_dot_mcp__pb2.ManageMcpRequest.SerializeToString,
                response_deserializer=aiflow_dot_v1_dot_mcp__pb2.ManageMcpResponse.FromString,
                _registered_method=True)


class McpServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ManageMcp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_McpServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ManageMcp': grpc.unary_unary_rpc_method_handler(
                    servicer.ManageMcp,
                    request_deserializer=aiflow_dot_v1_dot_mcp__pb2.ManageMcpRequest.FromString,
                    response_serializer=aiflow_dot_v1_dot_mcp__pb2.ManageMcpResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiflow.v1.McpService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiflow.v1.McpService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class McpService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ManageMcp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiflow.v1.McpService/ManageMcp',
            aiflow_dot_v1_dot_mcp__pb2.ManageMcpRequest.SerializeToString,
            aiflow_dot_v1_dot_mcp__pb2.ManageMcpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
