# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aiflow.v1 import models_pb2 as aiflow_dot_v1_dot_models__pb2


class ModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListModels = channel.unary_unary(
                '/aiflow.v1.ModelService/ListModels',
                request_serializer=aiflow_dot_v1_dot_models__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=aiflow_dot_v1_dot_models__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/aiflow.v1.ModelService/HealthCheck',
                request_serializer=aiflow_dot_v1_dot_models__pb2.ModelServiceHealthCheckRequest.SerializeToString,
                response_deserializer=aiflow_dot_v1_dot_models__pb2.ModelServiceHealthCheckResponse.FromString,
                _registered_method=True)


class ModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=aiflow_dot_v1_dot_models__pb2.ListModelsRequest.FromString,
                    response_serializer=aiflow_dot_v1_dot_models__pb2.ListModelsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=aiflow_dot_v1_dot_models__pb2.ModelServiceHealthCheckRequest.FromString,
                    response_serializer=aiflow_dot_v1_dot_models__pb2.ModelServiceHealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiflow.v1.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiflow.v1.ModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiflow.v1.ModelService/ListModels',
            aiflow_dot_v1_dot_models__pb2.ListModelsRequest.SerializeToString,
            aiflow_dot_v1_dot_models__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiflow.v1.ModelService/HealthCheck',
            aiflow_dot_v1_dot_models__pb2.ModelServiceHealthCheckRequest.SerializeToString,
            aiflow_dot_v1_dot_models__pb2.ModelServiceHealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
