# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aiflow.v1 import retrieval_pb2 as aiflow_dot_v1_dot_retrieval__pb2


class RetrievalServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Retrieve = channel.unary_unary(
                '/aiflow.v1.RetrievalService/Retrieve',
                request_serializer=aiflow_dot_v1_dot_retrieval__pb2.RetrieveRequest.SerializeToString,
                response_deserializer=aiflow_dot_v1_dot_retrieval__pb2.RetrieveResponse.FromString,
                _registered_method=True)


class RetrievalServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RetrievalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=aiflow_dot_v1_dot_retrieval__pb2.RetrieveRequest.FromString,
                    response_serializer=aiflow_dot_v1_dot_retrieval__pb2.RetrieveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiflow.v1.RetrievalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiflow.v1.RetrievalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RetrievalService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiflow.v1.RetrievalService/Retrieve',
            aiflow_dot_v1_dot_retrieval__pb2.RetrieveRequest.SerializeToString,
            aiflow_dot_v1_dot_retrieval__pb2.RetrieveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
