# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aiflow.v1 import sandbox_pb2 as aiflow_dot_v1_dot_sandbox__pb2


class SandboxServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecutePython = channel.unary_unary(
                '/aiflow.v1.SandboxService/ExecutePython',
                request_serializer=aiflow_dot_v1_dot_sandbox__pb2.ExecutePythonRequest.SerializeToString,
                response_deserializer=aiflow_dot_v1_dot_sandbox__pb2.ExecutePythonResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/aiflow.v1.SandboxService/HealthCheck',
                request_serializer=aiflow_dot_v1_dot_sandbox__pb2.SandboxServiceHealthCheckRequest.SerializeToString,
                response_deserializer=aiflow_dot_v1_dot_sandbox__pb2.SandboxServiceHealthCheckResponse.FromString,
                _registered_method=True)


class SandboxServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecutePython(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecutePython': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutePython,
                    request_deserializer=aiflow_dot_v1_dot_sandbox__pb2.ExecutePythonRequest.FromString,
                    response_serializer=aiflow_dot_v1_dot_sandbox__pb2.ExecutePythonResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=aiflow_dot_v1_dot_sandbox__pb2.SandboxServiceHealthCheckRequest.FromString,
                    response_serializer=aiflow_dot_v1_dot_sandbox__pb2.SandboxServiceHealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiflow.v1.SandboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiflow.v1.SandboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecutePython(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiflow.v1.SandboxService/ExecutePython',
            aiflow_dot_v1_dot_sandbox__pb2.ExecutePythonRequest.SerializeToString,
            aiflow_dot_v1_dot_sandbox__pb2.ExecutePythonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiflow.v1.SandboxService/HealthCheck',
            aiflow_dot_v1_dot_sandbox__pb2.SandboxServiceHealthCheckRequest.SerializeToString,
            aiflow_dot_v1_dot_sandbox__pb2.SandboxServiceHealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
