// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package controlstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO control.api_keys (
    name,
    key_digest,
    key_prefix,
    scopes,
    expires_at,
    user_id,
    application_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, key_digest, key_prefix, scopes, is_active, last_used_at,
          expires_at, user_id, application_id, created_at
`

type CreateAPIKeyParams struct {
	Name          string             `json:"name"`
	KeyDigest     []byte             `json:"key_digest"`
	KeyPrefix     string             `json:"key_prefix"`
	Scopes        []byte             `json:"scopes"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	UserID        pgtype.UUID        `json:"user_id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ControlApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.Name,
		arg.KeyDigest,
		arg.KeyPrefix,
		arg.Scopes,
		arg.ExpiresAt,
		arg.UserID,
		arg.ApplicationID,
	)
	var i ControlApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyDigest,
		&i.KeyPrefix,
		&i.Scopes,
		&i.IsActive,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.UserID,
		&i.ApplicationID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :one
DELETE FROM control.api_keys
WHERE id = $1 AND user_id = $2
RETURNING id
`

type DeleteAPIKeyParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteAPIKey, arg.ID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getAPIKeyByDigest = `-- name: GetAPIKeyByDigest :one
SELECT id, name, key_digest, key_prefix, scopes, is_active, last_used_at,
       expires_at, user_id, application_id, created_at
FROM control.api_keys
WHERE key_digest = $1
`

func (q *Queries) GetAPIKeyByDigest(ctx context.Context, keyDigest []byte) (ControlApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByDigest, keyDigest)
	var i ControlApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyDigest,
		&i.KeyPrefix,
		&i.Scopes,
		&i.IsActive,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.UserID,
		&i.ApplicationID,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, name, key_digest, key_prefix, scopes, is_active, last_used_at,
       expires_at, user_id, application_id, created_at
FROM control.api_keys
WHERE id = $1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ControlApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i ControlApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyDigest,
		&i.KeyPrefix,
		&i.Scopes,
		&i.IsActive,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.UserID,
		&i.ApplicationID,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, key_digest, key_prefix, scopes, is_active, last_used_at,
       expires_at, user_id, application_id, created_at
FROM control.api_keys
WHERE user_id = $1::uuid
  AND (
      $2::uuid IS NULL
      OR application_id = $2::uuid
  )
ORDER BY created_at DESC, id
`

type ListAPIKeysParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	ApplicationID pgtype.UUID `json:"application_id"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ControlApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, arg.UserID, arg.ApplicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlApiKey{}
	for rows.Next() {
		var i ControlApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyDigest,
			&i.KeyPrefix,
			&i.Scopes,
			&i.IsActive,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.UserID,
			&i.ApplicationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAPIKeyActive = `-- name: SetAPIKeyActive :one
UPDATE control.api_keys
SET is_active = $3
WHERE id = $1 AND user_id = $2
RETURNING id, name, key_digest, key_prefix, scopes, is_active, last_used_at,
          expires_at, user_id, application_id, created_at
`

type SetAPIKeyActiveParams struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) SetAPIKeyActive(ctx context.Context, arg SetAPIKeyActiveParams) (ControlApiKey, error) {
	row := q.db.QueryRow(ctx, setAPIKeyActive, arg.ID, arg.UserID, arg.IsActive)
	var i ControlApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyDigest,
		&i.KeyPrefix,
		&i.Scopes,
		&i.IsActive,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.UserID,
		&i.ApplicationID,
		&i.CreatedAt,
	)
	return i, err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE control.api_keys
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
