// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package controlstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO control.applications (name, description, icon, status, owner_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, icon, status, share_link, owner_id, created_at, updated_at
`

type CreateApplicationParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Icon        pgtype.Text `json:"icon"`
	Status      string      `json:"status"`
	OwnerID     pgtype.UUID `json:"owner_id"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (ControlApplication, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Status,
		arg.OwnerID,
	)
	var i ControlApplication
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Status,
		&i.ShareLink,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :one
DELETE FROM control.applications
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteApplication(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteApplication, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, name, description, icon, status, share_link, owner_id, created_at, updated_at
FROM control.applications
WHERE id = $1
`

func (q *Queries) GetApplicationByID(ctx context.Context, id pgtype.UUID) (ControlApplication, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, id)
	var i ControlApplication
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Status,
		&i.ShareLink,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationOwnerID = `-- name: GetApplicationOwnerID :one
SELECT owner_id
FROM control.applications
WHERE id = $1
`

func (q *Queries) GetApplicationOwnerID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getApplicationOwnerID, id)
	var owner_id pgtype.UUID
	err := row.Scan(&owner_id)
	return owner_id, err
}

const listApplicationAccessForUser = `-- name: ListApplicationAccessForUser :many
SELECT a.owner_id,
       u.global_role,
       tm.role AS team_role,
       ta.permission AS team_application_permission
FROM control.applications AS a
CROSS JOIN control.users AS u
LEFT JOIN control.team_applications AS ta
    ON ta.application_id = a.id
LEFT JOIN control.team_members AS tm
    ON tm.team_id = ta.team_id
   AND tm.user_id = u.id
WHERE a.id = $1::uuid
  AND u.id = $2::uuid
`

type ListApplicationAccessForUserParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	UserID        pgtype.UUID `json:"user_id"`
}

type ListApplicationAccessForUserRow struct {
	OwnerID                   pgtype.UUID `json:"owner_id"`
	GlobalRole                string      `json:"global_role"`
	TeamRole                  pgtype.Text `json:"team_role"`
	TeamApplicationPermission pgtype.Text `json:"team_application_permission"`
}

func (q *Queries) ListApplicationAccessForUser(ctx context.Context, arg ListApplicationAccessForUserParams) ([]ListApplicationAccessForUserRow, error) {
	rows, err := q.db.Query(ctx, listApplicationAccessForUser, arg.ApplicationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationAccessForUserRow{}
	for rows.Next() {
		var i ListApplicationAccessForUserRow
		if err := rows.Scan(
			&i.OwnerID,
			&i.GlobalRole,
			&i.TeamRole,
			&i.TeamApplicationPermission,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsForUser = `-- name: ListApplicationsForUser :many
WITH application_access AS (
    SELECT a.id AS application_id, 'owner'::text AS access_type, 4 AS access_rank
    FROM control.applications AS a
    WHERE a.owner_id = $1::uuid

    UNION ALL

    SELECT ta.application_id,
           ta.permission AS access_type,
           CASE ta.permission
               WHEN 'full_access' THEN 3
               WHEN 'can_edit' THEN 2
               ELSE 1
           END AS access_rank
    FROM control.team_applications AS ta
    JOIN control.team_members AS tm ON tm.team_id = ta.team_id
    WHERE tm.user_id = $1::uuid
),
best_access AS (
    SELECT application_id,
           (array_agg(access_type ORDER BY access_rank DESC))[1] AS access_type
    FROM application_access
    GROUP BY application_id
)
SELECT a.id,
       a.name,
       a.description,
       a.icon,
       a.status,
       a.share_link,
       a.owner_id,
       a.created_at,
       a.updated_at,
       best_access.access_type
FROM control.applications AS a
JOIN best_access ON best_access.application_id = a.id
ORDER BY a.updated_at DESC, a.id
`

type ListApplicationsForUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Icon        pgtype.Text        `json:"icon"`
	Status      string             `json:"status"`
	ShareLink   pgtype.Text        `json:"share_link"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	AccessType  interface{}        `json:"access_type"`
}

func (q *Queries) ListApplicationsForUser(ctx context.Context, userID pgtype.UUID) ([]ListApplicationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsForUserRow{}
	for rows.Next() {
		var i ListApplicationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Status,
			&i.ShareLink,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccessType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setApplicationShareLink = `-- name: SetApplicationShareLink :exec
UPDATE control.applications
SET share_link = $2
WHERE id = $1
`

type SetApplicationShareLinkParams struct {
	ID        pgtype.UUID `json:"id"`
	ShareLink pgtype.Text `json:"share_link"`
}

func (q *Queries) SetApplicationShareLink(ctx context.Context, arg SetApplicationShareLinkParams) error {
	_, err := q.db.Exec(ctx, setApplicationShareLink, arg.ID, arg.ShareLink)
	return err
}

const setApplicationStatus = `-- name: SetApplicationStatus :one
UPDATE control.applications
SET status = $2
WHERE id = $1
RETURNING id, name, description, icon, status, share_link, owner_id, created_at, updated_at
`

type SetApplicationStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) SetApplicationStatus(ctx context.Context, arg SetApplicationStatusParams) (ControlApplication, error) {
	row := q.db.QueryRow(ctx, setApplicationStatus, arg.ID, arg.Status)
	var i ControlApplication
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Status,
		&i.ShareLink,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE control.applications
SET name = CASE
        WHEN $1::boolean THEN $2::text
        ELSE name
    END,
    description = CASE
        WHEN $3::boolean THEN $4::text
        ELSE description
    END,
    icon = CASE
        WHEN $5::boolean THEN $6::text
        ELSE icon
    END,
    status = CASE
        WHEN $7::boolean THEN $8::text
        ELSE status
    END
WHERE id = $9::uuid
RETURNING id, name, description, icon, status, share_link, owner_id, created_at, updated_at
`

type UpdateApplicationParams struct {
	SetName        bool        `json:"set_name"`
	Name           string      `json:"name"`
	SetDescription bool        `json:"set_description"`
	Description    pgtype.Text `json:"description"`
	SetIcon        bool        `json:"set_icon"`
	Icon           pgtype.Text `json:"icon"`
	SetStatus      bool        `json:"set_status"`
	Status         string      `json:"status"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (ControlApplication, error) {
	row := q.db.QueryRow(ctx, updateApplication,
		arg.SetName,
		arg.Name,
		arg.SetDescription,
		arg.Description,
		arg.SetIcon,
		arg.Icon,
		arg.SetStatus,
		arg.Status,
		arg.ID,
	)
	var i ControlApplication
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Status,
		&i.ShareLink,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
