// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package controlstore

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1::bigint AS value
`

func (q *Queries) Ping(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, ping)
	var value int64
	err := row.Scan(&value)
	return value, err
}
