// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package controlstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppShare = `-- name: CreateAppShare :one
INSERT INTO control.app_shares (application_id, share_link, is_public)
VALUES ($1, $2, $3)
RETURNING id, application_id, share_link, is_public, access_count, embed_config,
          created_at, updated_at
`

type CreateAppShareParams struct {
	ApplicationID pgtype.UUID `json:"application_id"`
	ShareLink     string      `json:"share_link"`
	IsPublic      bool        `json:"is_public"`
}

func (q *Queries) CreateAppShare(ctx context.Context, arg CreateAppShareParams) (ControlAppShare, error) {
	row := q.db.QueryRow(ctx, createAppShare, arg.ApplicationID, arg.ShareLink, arg.IsPublic)
	var i ControlAppShare
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ShareLink,
		&i.IsPublic,
		&i.AccessCount,
		&i.EmbedConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAppShare = `-- name: DeleteAppShare :one
DELETE FROM control.app_shares
WHERE application_id = $1
RETURNING id
`

func (q *Queries) DeleteAppShare(ctx context.Context, applicationID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteAppShare, applicationID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getAppShareByApplicationID = `-- name: GetAppShareByApplicationID :one
SELECT id, application_id, share_link, is_public, access_count, embed_config,
       created_at, updated_at
FROM control.app_shares
WHERE application_id = $1
`

func (q *Queries) GetAppShareByApplicationID(ctx context.Context, applicationID pgtype.UUID) (ControlAppShare, error) {
	row := q.db.QueryRow(ctx, getAppShareByApplicationID, applicationID)
	var i ControlAppShare
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ShareLink,
		&i.IsPublic,
		&i.AccessCount,
		&i.EmbedConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicAppShareByLink = `-- name: GetPublicAppShareByLink :one
SELECT s.id,
       s.application_id,
       s.share_link,
       s.is_public,
       s.access_count,
       s.embed_config,
       s.created_at,
       s.updated_at,
       a.name,
       a.description,
       a.icon,
       a.status
FROM control.app_shares AS s
JOIN control.applications AS a ON a.id = s.application_id
WHERE s.share_link = $1 AND s.is_public = true
`

type GetPublicAppShareByLinkRow struct {
	ID            pgtype.UUID        `json:"id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	ShareLink     string             `json:"share_link"`
	IsPublic      bool               `json:"is_public"`
	AccessCount   int32              `json:"access_count"`
	EmbedConfig   []byte             `json:"embed_config"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	Icon          pgtype.Text        `json:"icon"`
	Status        string             `json:"status"`
}

func (q *Queries) GetPublicAppShareByLink(ctx context.Context, shareLink string) (GetPublicAppShareByLinkRow, error) {
	row := q.db.QueryRow(ctx, getPublicAppShareByLink, shareLink)
	var i GetPublicAppShareByLinkRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ShareLink,
		&i.IsPublic,
		&i.AccessCount,
		&i.EmbedConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Status,
	)
	return i, err
}

const incrementAppShareAccess = `-- name: IncrementAppShareAccess :exec
UPDATE control.app_shares
SET access_count = access_count + 1
WHERE id = $1
`

func (q *Queries) IncrementAppShareAccess(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementAppShareAccess, id)
	return err
}

const updateAppShare = `-- name: UpdateAppShare :one
UPDATE control.app_shares
SET is_public = CASE
        WHEN $1::boolean THEN $2::boolean
        ELSE is_public
    END,
    embed_config = CASE
        WHEN $3::boolean THEN $4::jsonb
        ELSE embed_config
    END
WHERE application_id = $5::uuid
RETURNING id, application_id, share_link, is_public, access_count, embed_config,
          created_at, updated_at
`

type UpdateAppShareParams struct {
	SetIsPublic    bool        `json:"set_is_public"`
	IsPublic       bool        `json:"is_public"`
	SetEmbedConfig bool        `json:"set_embed_config"`
	EmbedConfig    []byte      `json:"embed_config"`
	ApplicationID  pgtype.UUID `json:"application_id"`
}

func (q *Queries) UpdateAppShare(ctx context.Context, arg UpdateAppShareParams) (ControlAppShare, error) {
	row := q.db.QueryRow(ctx, updateAppShare,
		arg.SetIsPublic,
		arg.IsPublic,
		arg.SetEmbedConfig,
		arg.EmbedConfig,
		arg.ApplicationID,
	)
	var i ControlAppShare
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.ShareLink,
		&i.IsPublic,
		&i.AccessCount,
		&i.EmbedConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
