// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package controlstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO control.teams (name, description, avatar, owner_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, avatar, owner_id, created_at, updated_at
`

type CreateTeamParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Avatar      pgtype.Text `json:"avatar"`
	OwnerID     pgtype.UUID `json:"owner_id"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (ControlTeam, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.Name,
		arg.Description,
		arg.Avatar,
		arg.OwnerID,
	)
	var i ControlTeam
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Avatar,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeamApplication = `-- name: CreateTeamApplication :one
INSERT INTO control.team_applications (team_id, application_id, permission)
VALUES ($1, $2, $3)
RETURNING id, team_id, application_id, permission, added_at
`

type CreateTeamApplicationParams struct {
	TeamID        pgtype.UUID `json:"team_id"`
	ApplicationID pgtype.UUID `json:"application_id"`
	Permission    string      `json:"permission"`
}

func (q *Queries) CreateTeamApplication(ctx context.Context, arg CreateTeamApplicationParams) (ControlTeamApplication, error) {
	row := q.db.QueryRow(ctx, createTeamApplication, arg.TeamID, arg.ApplicationID, arg.Permission)
	var i ControlTeamApplication
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ApplicationID,
		&i.Permission,
		&i.AddedAt,
	)
	return i, err
}

const createTeamMember = `-- name: CreateTeamMember :one
INSERT INTO control.team_members (team_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, team_id, user_id, role, joined_at
`

type CreateTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) CreateTeamMember(ctx context.Context, arg CreateTeamMemberParams) (ControlTeamMember, error) {
	row := q.db.QueryRow(ctx, createTeamMember, arg.TeamID, arg.UserID, arg.Role)
	var i ControlTeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :one
DELETE FROM control.teams
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteTeam(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteTeam, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const deleteTeamApplication = `-- name: DeleteTeamApplication :one
DELETE FROM control.team_applications
WHERE team_id = $1 AND id = $2
RETURNING id
`

type DeleteTeamApplicationParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteTeamApplication(ctx context.Context, arg DeleteTeamApplicationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteTeamApplication, arg.TeamID, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteTeamMember = `-- name: DeleteTeamMember :one
DELETE FROM control.team_members
WHERE team_id = $1 AND id = $2
RETURNING id
`

type DeleteTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteTeamMember(ctx context.Context, arg DeleteTeamMemberParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteTeamMember, arg.TeamID, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteTeamMembershipByUser = `-- name: DeleteTeamMembershipByUser :one
DELETE FROM control.team_members
WHERE team_id = $1 AND user_id = $2
RETURNING id
`

type DeleteTeamMembershipByUserParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteTeamMembershipByUser(ctx context.Context, arg DeleteTeamMembershipByUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteTeamMembershipByUser, arg.TeamID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getTeamApplicationByID = `-- name: GetTeamApplicationByID :one
SELECT id, team_id, application_id, permission, added_at
FROM control.team_applications
WHERE id = $1
`

func (q *Queries) GetTeamApplicationByID(ctx context.Context, id pgtype.UUID) (ControlTeamApplication, error) {
	row := q.db.QueryRow(ctx, getTeamApplicationByID, id)
	var i ControlTeamApplication
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ApplicationID,
		&i.Permission,
		&i.AddedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, description, avatar, owner_id, created_at, updated_at
FROM control.teams
WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id pgtype.UUID) (ControlTeam, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i ControlTeam
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Avatar,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMemberByID = `-- name: GetTeamMemberByID :one
SELECT id, team_id, user_id, role, joined_at
FROM control.team_members
WHERE id = $1
`

func (q *Queries) GetTeamMemberByID(ctx context.Context, id pgtype.UUID) (ControlTeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMemberByID, id)
	var i ControlTeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getTeamMembership = `-- name: GetTeamMembership :one
SELECT id, team_id, user_id, role, joined_at
FROM control.team_members
WHERE team_id = $1 AND user_id = $2
`

type GetTeamMembershipParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTeamMembership(ctx context.Context, arg GetTeamMembershipParams) (ControlTeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMembership, arg.TeamID, arg.UserID)
	var i ControlTeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const listTeamApplications = `-- name: ListTeamApplications :many
SELECT ta.id,
       ta.team_id,
       ta.application_id,
       ta.permission,
       ta.added_at,
       a.name,
       a.description,
       a.icon,
       a.status
FROM control.team_applications AS ta
JOIN control.applications AS a ON a.id = ta.application_id
WHERE ta.team_id = $1
ORDER BY ta.added_at, ta.id
`

type ListTeamApplicationsRow struct {
	ID            pgtype.UUID        `json:"id"`
	TeamID        pgtype.UUID        `json:"team_id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
	Permission    string             `json:"permission"`
	AddedAt       pgtype.Timestamptz `json:"added_at"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	Icon          pgtype.Text        `json:"icon"`
	Status        string             `json:"status"`
}

func (q *Queries) ListTeamApplications(ctx context.Context, teamID pgtype.UUID) ([]ListTeamApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listTeamApplications, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamApplicationsRow{}
	for rows.Next() {
		var i ListTeamApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ApplicationID,
			&i.Permission,
			&i.AddedAt,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT tm.id,
       tm.team_id,
       tm.user_id,
       tm.role,
       tm.joined_at,
       u.username,
       u.avatar,
       u.created_at AS user_created_at
FROM control.team_members AS tm
JOIN control.users AS u ON u.id = tm.user_id
WHERE tm.team_id = $1
ORDER BY tm.joined_at, tm.id
`

type ListTeamMembersRow struct {
	ID            pgtype.UUID        `json:"id"`
	TeamID        pgtype.UUID        `json:"team_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Role          string             `json:"role"`
	JoinedAt      pgtype.Timestamptz `json:"joined_at"`
	Username      string             `json:"username"`
	Avatar        pgtype.Text        `json:"avatar"`
	UserCreatedAt pgtype.Timestamptz `json:"user_created_at"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Username,
			&i.Avatar,
			&i.UserCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForUser = `-- name: ListTeamsForUser :many
SELECT t.id,
       t.name,
       t.description,
       t.avatar,
       t.owner_id,
       t.created_at,
       t.updated_at,
       membership.role AS my_role,
       (SELECT count(*) FROM control.team_members AS members WHERE members.team_id = t.id) AS member_count,
       (SELECT count(*) FROM control.team_applications AS apps WHERE apps.team_id = t.id) AS app_count
FROM control.teams AS t
JOIN control.team_members AS membership
  ON membership.team_id = t.id
 AND membership.user_id = $1
ORDER BY t.updated_at DESC, t.id
`

type ListTeamsForUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Avatar      pgtype.Text        `json:"avatar"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	MyRole      string             `json:"my_role"`
	MemberCount int64              `json:"member_count"`
	AppCount    int64              `json:"app_count"`
}

func (q *Queries) ListTeamsForUser(ctx context.Context, userID pgtype.UUID) ([]ListTeamsForUserRow, error) {
	rows, err := q.db.Query(ctx, listTeamsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsForUserRow{}
	for rows.Next() {
		var i ListTeamsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Avatar,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MyRole,
			&i.MemberCount,
			&i.AppCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE control.teams
SET name = CASE
        WHEN $1::boolean THEN $2::text
        ELSE name
    END,
    description = CASE
        WHEN $3::boolean THEN $4::text
        ELSE description
    END,
    avatar = CASE
        WHEN $5::boolean THEN $6::text
        ELSE avatar
    END
WHERE id = $7::uuid
RETURNING id, name, description, avatar, owner_id, created_at, updated_at
`

type UpdateTeamParams struct {
	SetName        bool        `json:"set_name"`
	Name           string      `json:"name"`
	SetDescription bool        `json:"set_description"`
	Description    pgtype.Text `json:"description"`
	SetAvatar      bool        `json:"set_avatar"`
	Avatar         pgtype.Text `json:"avatar"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (ControlTeam, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.SetName,
		arg.Name,
		arg.SetDescription,
		arg.Description,
		arg.SetAvatar,
		arg.Avatar,
		arg.ID,
	)
	var i ControlTeam
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Avatar,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeamApplicationPermission = `-- name: UpdateTeamApplicationPermission :one
UPDATE control.team_applications
SET permission = $3
WHERE team_id = $1 AND id = $2
RETURNING id, team_id, application_id, permission, added_at
`

type UpdateTeamApplicationPermissionParams struct {
	TeamID     pgtype.UUID `json:"team_id"`
	ID         pgtype.UUID `json:"id"`
	Permission string      `json:"permission"`
}

func (q *Queries) UpdateTeamApplicationPermission(ctx context.Context, arg UpdateTeamApplicationPermissionParams) (ControlTeamApplication, error) {
	row := q.db.QueryRow(ctx, updateTeamApplicationPermission, arg.TeamID, arg.ID, arg.Permission)
	var i ControlTeamApplication
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ApplicationID,
		&i.Permission,
		&i.AddedAt,
	)
	return i, err
}

const updateTeamMemberRole = `-- name: UpdateTeamMemberRole :one
UPDATE control.team_members
SET role = $3
WHERE team_id = $1 AND id = $2
RETURNING id, team_id, user_id, role, joined_at
`

type UpdateTeamMemberRoleParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	ID     pgtype.UUID `json:"id"`
	Role   string      `json:"role"`
}

func (q *Queries) UpdateTeamMemberRole(ctx context.Context, arg UpdateTeamMemberRoleParams) (ControlTeamMember, error) {
	row := q.db.QueryRow(ctx, updateTeamMemberRole, arg.TeamID, arg.ID, arg.Role)
	var i ControlTeamMember
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
