// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package controlstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO control.users (username, password_hash)
VALUES ($1, $2)
RETURNING id, username, password_hash, avatar, global_role, created_at, updated_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (ControlUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash)
	var i ControlUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Avatar,
		&i.GlobalRole,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, avatar, global_role, created_at, updated_at
FROM control.users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (ControlUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i ControlUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Avatar,
		&i.GlobalRole,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, avatar, global_role, created_at, updated_at
FROM control.users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (ControlUser, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i ControlUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Avatar,
		&i.GlobalRole,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserGlobalRole = `-- name: GetUserGlobalRole :one
SELECT global_role
FROM control.users
WHERE id = $1
`

func (q *Queries) GetUserGlobalRole(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserGlobalRole, id)
	var global_role string
	err := row.Scan(&global_role)
	return global_role, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE control.users
SET username = CASE
        WHEN $1::boolean THEN $2::text
        ELSE username
    END,
    avatar = CASE
        WHEN $3::boolean THEN $4::text
        ELSE avatar
    END
WHERE id = $5::uuid
RETURNING id, username, password_hash, avatar, global_role, created_at, updated_at
`

type UpdateUserProfileParams struct {
	SetUsername bool        `json:"set_username"`
	Username    string      `json:"username"`
	SetAvatar   bool        `json:"set_avatar"`
	Avatar      pgtype.Text `json:"avatar"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (ControlUser, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.SetUsername,
		arg.Username,
		arg.SetAvatar,
		arg.Avatar,
		arg.ID,
	)
	var i ControlUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Avatar,
		&i.GlobalRole,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
